name: repo_tests
on: [workflow_dispatch, workflow_call]

jobs:
  repo_test:
    name: trunk-action in ${{ matrix.repo }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        repo:
          - jbeder/yaml-cpp
          #- replayio/devtools
          #- square/leakcanary
          #- terraform-linters/tflint
          #- trunk-io/plugins
          #- z-shell/wiki

    steps:
      - name: Checkout repo under test
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}

      - name: Checkout action
        uses: actions/checkout@v3
        with:
          path: local-action

      - name: Run trunk-action
        id: trunk
        uses: ./local-action/
        with:
          check-mode: all

      - name: Check for linter/task failures
        if: always()
        shell: python
        run: |
          import json, sys

          landing_state = json.loads("${{ steps.trunk.outputs.landing-state }}")
          failure_count = len(landing_state.get("taskFailures", []))

          if failure_count == 0:
            sys.exit(0)

          if failure_count == 1:
            print(f'There was {failure_count} task failure')
          else:
            print(f'There were {failure_count} task failures')
          print('Failures can be viewed in the logs for the previous step')
          sys.exit(1)
